# Generated by Django 2.2.3 on 2019-09-26 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(default='admin', max_length=35, verbose_name='Firstname'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='login',
            field=models.CharField(default='admin', max_length=25, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='secondname',
            field=models.CharField(default='admin', max_length=35, verbose_name='Secondname'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active User'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff'),
        ),
    ]
