# Generated by Django 2.2.3 on 2019-09-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190926_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(max_length=35, null=True, verbose_name='Firstname'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='login',
            field=models.CharField(max_length=25, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='secondname',
            field=models.CharField(max_length=35, null=True, verbose_name='Secondname'),
        ),
    ]
